// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCeuvWUxCf6ugYhMxbD0tD9qqwS7sn5Ik',
    appId: '1:351864632613:android:8342833aa99d868fcc16cc',
    messagingSenderId: '351864632613',
    projectId: 'social-network-85e36',
    storageBucket: 'social-network-85e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXa3H6KpiYhqDT-KVdXDpjhzevdwfA1gE',
    appId: '1:351864632613:ios:181b60577f243c79cc16cc',
    messagingSenderId: '351864632613',
    projectId: 'social-network-85e36',
    storageBucket: 'social-network-85e36.appspot.com',
    iosClientId: '351864632613-15k1c6dh60870v2nlesleh86nbfkq649.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccvc',
  );
}
